"""added cascade ondelete and nullable True for user_id in Invite

Revision ID: 0f2d64315fbc
Revises: 115b7f4e32bc
Create Date: 2025-10-20 16:11:32.546249

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0f2d64315fbc"
down_revision: Union[str, None] = "115b7f4e32bc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("events_host_id_fkey"), "events", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "events", "users", ["host_id"], ["id"], ondelete="CASCADE"
    )
    op.add_column("invites", sa.Column("user_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None, "invites", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "invites", type_="foreignkey")
    op.drop_column("invites", "user_id")
    op.drop_constraint(None, "events", type_="foreignkey")
    op.create_foreign_key(
        op.f("events_host_id_fkey"), "events", "users", ["host_id"], ["id"]
    )
    # ### end Alembic commands ###
