"""added cascade to Event, EventParticipant, and Invite

Revision ID: 115b7f4e32bc
Revises: d8a5e897ac99
Create Date: 2025-10-20 15:53:39.428041

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "115b7f4e32bc"
down_revision: Union[str, None] = "d8a5e897ac99"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("event_participants_user_id_fkey"),
        "event_participants",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("event_participants_event_id_fkey"),
        "event_participants",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "event_participants",
        "events",
        ["event_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        None,
        "event_participants",
        "users",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint(
        op.f("invites_event_id_fkey"), "invites", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "invites", "events", ["event_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "invites", type_="foreignkey")
    op.create_foreign_key(
        op.f("invites_event_id_fkey"),
        "invites",
        "events",
        ["event_id"],
        ["id"],
    )
    op.drop_constraint(None, "event_participants", type_="foreignkey")
    op.drop_constraint(None, "event_participants", type_="foreignkey")
    op.create_foreign_key(
        op.f("event_participants_event_id_fkey"),
        "event_participants",
        "events",
        ["event_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("event_participants_user_id_fkey"),
        "event_participants",
        "users",
        ["user_id"],
        ["id"],
    )
    # ### end Alembic commands ###
