"""Add patient_profiles table

Revision ID: 18fc693558b8
Revises: 291b4ba80041
Create Date: 2025-06-27 19:13:45.729860

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "18fc693558b8"
down_revision: Union[str, None] = "291b4ba80041"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "patient_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("dob", sa.Date(), nullable=False),
        sa.Column("phone", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "name", "dob", "phone", name="uq_patient_identity"
        ),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(
        op.f("ix_patient_profiles_id"),
        "patient_profiles",
        ["id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_patient_profiles_id"), table_name="patient_profiles"
    )
    op.drop_table("patient_profiles")
    # ### end Alembic commands ###
