"""revised event column names

Revision ID: 5f9dfde3eb20
Revises: 68df65017c79
Create Date: 2025-11-24 22:45:31.505156

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5f9dfde3eb20"
down_revision: Union[str, None] = "68df65017c79"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "events",
        sa.Column(
            "start_time",
            sa.DateTime(),
            nullable=False,
            server_default=sa.text("'2025-01-01 00:00:00'"),
        ),
    )
    op.add_column(
        "events",
        sa.Column(
            "end_time",
            sa.DateTime(),
            nullable=False,
            server_default=sa.text("'2025-01-02 00:00:00'"),
        ),
    )
    op.alter_column("events", "start_date", server_default=None)
    op.alter_column("events", "end_date", server_default=None)
    op.drop_column("events", "end_date")
    op.drop_column("events", "start_date")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "events",
        sa.Column(
            "start_date",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "events",
        sa.Column(
            "end_date",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("events", "end_time")
    op.drop_column("events", "start_time")
    # ### end Alembic commands ###
