"""added start_date and end_date

Revision ID: 68df65017c79
Revises: 9df32a1d2c9c
Create Date: 2025-11-24 22:26:28.008038

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "68df65017c79"
down_revision: Union[str, None] = "9df32a1d2c9c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "events",
        sa.Column(
            "start_date",
            sa.DateTime(),
            nullable=False,
            server_default=sa.text("'2025-01-01 00:00:00'"),
        ),
    )
    op.add_column(
        "events",
        sa.Column(
            "end_date",
            sa.DateTime(),
            nullable=False,
            server_default=sa.text("'2025-01-02 00:00:00'"),
        ),
    )
    op.alter_column("events", "start_date", server_default=None)
    op.alter_column("events", "end_date", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("events", "end_date")
    op.drop_column("events", "start_date")
    # ### end Alembic commands ###
