"""replaced datetime with TIMESTAMP

Revision ID: c01bbd3f3af4
Revises: 5f9dfde3eb20
Create Date: 2025-11-27 23:38:07.690435

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c01bbd3f3af4"
down_revision: Union[str, None] = "5f9dfde3eb20"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "events",
        "start_time",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text(
            "'2025-01-01 00:00:00'::timestamp without time zone"
        ),
    )
    op.alter_column(
        "events",
        "end_time",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text(
            "'2025-01-02 00:00:00'::timestamp without time zone"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "events",
        "end_time",
        existing_type=sa.TIMESTAMP(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text(
            "'2025-01-02 00:00:00'::timestamp without time zone"
        ),
    )
    op.alter_column(
        "events",
        "start_time",
        existing_type=sa.TIMESTAMP(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text(
            "'2025-01-01 00:00:00'::timestamp without time zone"
        ),
    )
    # ### end Alembic commands ###
