"""updated invite table

Revision ID: c9761932afb9
Revises: 92d4a7467697
Create Date: 2025-10-19 22:53:39.967001

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c9761932afb9"
down_revision: Union[str, None] = "92d4a7467697"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # Step 1: Add column as nullable
    op.add_column("invites", sa.Column("status", sa.String(), nullable=True))

    # Step 2: Set default value for existing rows
    op.execute("UPDATE invites SET status='pending' WHERE status IS NULL")

    # Step 3: Alter column to NOT NULL
    op.alter_column("invites", "status", nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "invites",
        sa.Column(
            "expires_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("invites", "status")
    # ### end Alembic commands ###
