# Build step
FROM node:20-alpine AS builder
WORKDIR /app

ARG UI_URL
ARG VITE_API_URL

ENV UI_URL=$UI_URL
ENV VITE_API_URL=$VITE_API_URL

COPY ui/ .
COPY .env.prod .env
RUN npm install && npm run build

# Serve static files with Nginx
FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
