FROM python:3.11-slim

WORKDIR /app

# Install only production dependencies
COPY ./requirements-prod.txt .
RUN pip install --no-cache-dir -r requirements-prod.txt


# Copy the app source and migration files
COPY ./src ./src
COPY ./alembic ./alembic
COPY ./alembic.ini .

# Entrypoint
CMD ["uvicorn", "src.main.main:app", "--host", "0.0.0.0", "--port", "9000"]
